# Generated by Django 5.2.17 on 2026-09-26 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='check_circle', max_length=40)),
                ('target_kind', models.CharField(choices=[('duration', 'Duration (minutes)'), ('count', 'Count'), ('check', 'Just do it')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('is_essential', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('core', 'Core'), ('standard', 'Standard'), ('optional', 'Optional')], max_length=10)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('planned_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('completion_ratio', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('partially_completed', 'Partially completed'), ('skipped', 'Skipped'), ('cancelled', 'Set aside')], default='pending', max_length=20)),
                ('skip_reason', models.CharField(blank=True, choices=[('no_time', 'Not enough time'), ('low_energy', 'Low energy'), ('not_relevant', 'Not relevant today'), ('other', 'Something else')], max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('running_since', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='routines.routineactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_date', models.DateField()),
                ('mode', models.CharField(choices=[('normal', 'Normal'), ('minimum', 'Minimum Day'), ('recovery', 'Recovery')], default='normal', max_length=10)),
                ('energy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recovery_dismissed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='tracking.activitycompletion')),
                ('daily_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='tracking.dailyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine_name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('work', 'Focus'), ('evening', 'Evening'), ('rest', 'Rest'), ('other', 'Other')], default='other', max_length=12)),
                ('local_date', models.DateField()),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('finish_by', models.DateTimeField(blank=True, null=True)),
                ('is_ad_hoc', models.BooleanField(default=False)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tracking.dailyplan')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('time_budget', 'Time budget'), ('minimum_day', 'Minimum Day'), ('recovery', 'Recovery')], max_length=12)),
                ('params', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='tracking.dailyplan')),
                ('routine_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='tracking.routineinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='routine_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracking.routineinstance'),
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(fields=('user', 'local_date'), name='tracking_plan_user_date'),
        ),
        migrations.AddConstraint(
            model_name='reflection',
            constraint=models.CheckConstraint(condition=models.Q(('completion__isnull', False), ('daily_plan__isnull', False), _connector='OR'), name='tracking_reflection_has_target'),
        ),
        migrations.AddIndex(
            model_name='routineinstance',
            index=models.Index(fields=['user', 'local_date'], name='tracking_ro_user_id_051a9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ad_hoc', False)), fields=('routine', 'local_date'), name='tracking_instance_routine_date'),
        ),
        migrations.AddIndex(
            model_name='activitycompletion',
            index=models.Index(fields=['user', 'status', 'completed_at'], name='tracking_ac_user_id_c49bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycompletion',
            index=models.Index(fields=['activity', 'completed_at'], name='tracking_ac_activit_0d01bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitycompletion',
            constraint=models.CheckConstraint(condition=models.Q(('completion_ratio__gte', 0), ('completion_ratio__lte', 1)), name='tracking_completion_ratio_range'),
        ),
    ]
