# Generated by Django 5.2.17 on 2026-09-26 11:09

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('work', 'Focus'), ('evening', 'Evening'), ('rest', 'Rest'), ('other', 'Other')], default='other', max_length=12)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]), blank=True, default=list, size=None)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_by', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=10)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='check_circle', max_length=40)),
                ('target_kind', models.CharField(choices=[('duration', 'Duration (minutes)'), ('count', 'Count'), ('check', 'Just do it')], default='duration', max_length=10)),
                ('target_value', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('is_essential', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('core', 'Core'), ('standard', 'Standard'), ('optional', 'Optional')], default='standard', max_length=10)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='goals.habit')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='routines.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'routine activities',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'status'], name='routines_ro_user_id_e96075_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineactivity',
            constraint=models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='routines_activity_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='routineactivity',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_value__isnull', True), models.Q(('minimum_value__gt', 0), ('minimum_value__lte', models.F('target_value'))), _connector='OR'), name='routines_activity_minimum_within_target'),
        ),
    ]
